version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "serve"]

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - MONGO_URL=${MONGO_URL}
      - CORS_WHITELIST_URL=${CORS_WHITELIST_URL}
      - PORT=${PORT}
    depends_on:
      - mongo
    command: ["npm", "start"]

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db

volumes:
  mongo-data:
